from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://demo4.msampleqa.in/login")
driver.find_element(By.XPATH,"//*[@formcontrolname='userId']").send_keys("1")
driver.find_element(By.XPATH,"//*[@type='password']").send_keys("Admin@123")
driver.find_element(By.XPATH,"//button[normalize-space()='Login']").click()
driver.implicitly_wait(10)
driver.find_element(By.XPATH,"//span[contains(text(),'Announcements')]").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//span[@class='single-view ng-star-inserted']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[contains(text(),'Add Book Events')]").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@placeholder='Event Type']/option[@value='4']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//textarea[@placeholder='Enter Description']").send_keys("Arts")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@placeholder='Facility Name']/option[@value='5']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//input[@placeholder='Enter Title']").send_keys("Arts and Crafts Workshop")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//input[@placeholder='Enter Number of Days']").send_keys("1")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//div[@class='mat-calendar-body-cell-content mat-focus-indicator mat-calendar-body-selected']")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@class='form-select ng-untouched ng-dirty ng-valid']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@class='form-select ng-untouched ng-star-inserted ng-dirty ng-valid']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[normalize-space()='Submit']").click()
driver.implicitly_wait(15)
if driver.current_url == "http://demo4.msampleqa.in/auth/event":
    print("Notice Added Successfully")
else:
    print("Add Notice Failed")
driver.quit()

