from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://demo4.msampleqa.in/login")
driver.find_element(By.XPATH,"//*[@formcontrolname='userId']").send_keys("1")
driver.find_element(By.XPATH,"//*[@type='password']").send_keys("Admin@123")
driver.find_element(By.XPATH,"//button[normalize-space()='Login']").click()
driver.implicitly_wait(10)
driver.find_element(By.XPATH,"//span[contains(text(),'Maintenance')]").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//body/app-root/app-layout[@class='ng-star-inserted']/div[@class='example-container']/mat-sidenav-container[@class='mat-drawer-container mat-sidenav-container example-sidenav-container']/mat-sidenav[@class='mat-drawer mat-sidenav slim-scroll ng-tns-c120-0 ng-trigger ng-trigger-transform ng-star-inserted mat-drawer-side']/div[@class='mat-drawer-inner-container ng-tns-c120-0']/mat-nav-list[@role='navigation']/div[@class='sidebar ng-star-inserted']/span[@class='ng-star-inserted']/mat-accordion[@class='mat-accordion mat-accordion-multi']/mat-expansion-panel[@class='mat-expansion-panel ng-tns-c100-5 ng-star-inserted mat-expanded mat-expansion-panel-spacing']/div[@id='cdk-accordion-child-2']/div[@class='mat-expansion-panel-body ng-tns-c100-5']/span[1]/span[1]/mat-list-item[1]/span[1]").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[contains(text(),'Add Maintenance Details')]").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//input[@placeholder='Invoice Number']").send_keys("INV030502")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//div[@class='mat-calendar-body-cell-content mat-focus-indicator mat-calendar-body-selected']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[@aria-label='Previous month']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//div[@class='mat-calendar-body-cell-content mat-focus-indicator mat-calendar-body-selected']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[@aria-label='Previous month']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//div[@class='mat-calendar-body-cell-content mat-focus-indicator mat-calendar-body-selected']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//div[@class='mat-calendar-body-cell-content mat-focus-indicator mat-calendar-body-selected']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@placeholder='categoryId']/option[@value='1050']").click()
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//input[@placeholder='Bill Amount']").send_keys("23444")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='gstPercentage']/option[@value='5']")
driver.implicitly_wait(5)
driver.find_element(By.XPATH,"//button[@class='button-uxcl mr-2']").click()
if driver.current_url == "http://demo4.msampleqa.in/auth/maintenance/mntlayout":
    print("Maintenance Added Successfully")
else:
    print("Add maintenance Failed")
driver.quit()