from selenium import webdriver
import time
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://demo4.msampleqa.in/login")
driver.find_element(By.XPATH,"//*[@formcontrolname='userId']").send_keys("1")
driver.find_element(By.XPATH,"//*[@type='password']").send_keys("Admin@123")
driver.find_element(By.XPATH,"//button[normalize-space()='Login']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[contains(text(),'Announcements')]").click()
time.sleep(5)
element = driver.find_element(By.XPATH, "//span[@class='mat-list-item-content']")
driver.execute_script("arguments[0].scrollIntoView(true);", element)
element.click()
time.sleep(10)
driver.find_element(By.XPATH,"//button[contains(text(),' Add Forum ')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//textarea[@placeholder='Enter Topic']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//textarea[@placeholder='Enter Topic']").send_keys("New Forum")
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='dropdown-btn']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[normalize-space()='UnSelect All']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//textarea[@placeholder='Enter Description']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//textarea[@placeholder='Enter Description']").send_keys("new")
time.sleep(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='keepQuestionForId']/option[@value='1']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@type='submit']").click()
time.sleep(15)
if driver.current_url == "http://demo4.msampleqa.in/auth/forum":
    print("Notice Added Successfully")
else:
    print("Add Notice Failed")
driver.quit()
