from selenium import webdriver
import time
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://demo4.msampleqa.in/login")
driver.find_element(By.XPATH,"//*[@formcontrolname='userId']").send_keys("1")
driver.find_element(By.XPATH,"//*[@type='password']").send_keys("Admin@123")
driver.find_element(By.XPATH,"//button[normalize-space()='Login']").click()
time.sleep(10)
side_panel = driver.find_element(By.XPATH,"/html/body/app-root/app-layout/div/mat-sidenav-container/mat-sidenav")
driver.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight;", side_panel)
driver.find_element(By.XPATH,"//span[contains(text(),'Announcements')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[@class='mat-list-item-content']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[contains(text(),'Add Schedule Meeting')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='row box-padding']//div[@class='row']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@class='form-select ng-untouched ng-star-inserted ng-dirty ng-valid']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@class='form-select ng-untouched ng-star-inserted ng-dirty ng-valid']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[normalize-space()='UnSelect All']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@class='form-select ng-untouched ng-star-inserted ng-dirty ng-valid']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[6]//div[1]//app-cmn-time-picker[1]//div[1]//input[1]").send_keys("8")
time.sleep(5)
driver.find_element(By.XPATH,"//div[6]//div[1]//app-cmn-time-picker[1]//div[1]//input[1]").send_keys("10")
time.sleep(5)
driver.find_element(By.XPATH,"//button[normalize-space()='Submit']").click()
time.sleep(15)
if driver.current_url == "http://demo4.msampleqa.in/auth/meetings":
    print("Poll Added Successfully")
else:
    print("Add Poll Failed")
time.sleep(5)
driver.quit()