from selenium import webdriver
import time
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://demo4.msampleqa.in/login")
driver.find_element(By.XPATH,"//*[@formcontrolname='userId']").send_keys("1")
driver.find_element(By.XPATH,"//*[@type='password']").send_keys("Admin@123")
driver.find_element(By.XPATH,"//button[normalize-space()='Login']").click()
time.sleep(10)
driver.find_element(By.XPATH,"//*[@id='mat-expansion-panel-header-0']/span[1]/mat-panel-title/div").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@class='child-name'][normalize-space()='Complaints']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[contains(text(),'Raise Complaint')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='categoryId']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='categoryId']/option[@value='2']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='priorityId']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//select[@formcontrolname='priorityId']/option[@value='3']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[contains(text(),'Select Assigned to')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[contains(text(),'Admin')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//span[contains(text(),'Select Notify To')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[normalize-space()='Owners']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[normalize-space()='Submit']").click()
time.sleep(15)
if driver.current_url == "http://demo4.msampleqa.in/auth/complaints":
    print("Complaint Added Successfully")
else:
    print("Failed to add a Complaint")

driver.quit()
